apiVersion: v1
kind: ConfigMap
metadata:
    name: grafana-alloy-config
    namespace: monitoring
data:
    config.alloy: |
        logging {
          level  = "info"
          format = "logfmt"
        }

        otelcol.receiver.otlp "default_metric" {
          http {
            endpoint="0.0.0.0:4318"
          }

          output {
            metrics  = [otelcol.processor.batch.default.input]
          }
        }

        otelcol.receiver.otlp "default" {
          http {
            endpoint="0.0.0.0:4320"
          }
          grpc {}

          output {
            traces   = [otelcol.processor.batch.default.input]
          }
        }

        otelcol.processor.batch "default" {
          output {
            metrics  = [otelcol.exporter.prometheus.default.input]
            traces   = [otelcol.exporter.otlphttp.tempo.input]
          }
        }

        otelcol.exporter.prometheus "default" {
            forward_to = [prometheus.remote_write.default.receiver]
        }

        prometheus.remote_write "default" {
            endpoint{
                url = "http://prometheus-service.monitoring.svc:9090/api/v1/write"
            }
        }

        otelcol.exporter.otlphttp "tempo" {
            client {
                endpoint = "http://tempo.monitoring.svc:4318"
                tls {
                    insecure             = true
                    insecure_skip_verify = true
                }
            }
        }
